### ISSUE TITLE
Images folder is empty

### ISSUE THREAD

**Issue by jvmunhoz** [Atemu/bookwalker-dl#6]
**OS:** Pop!_OS 19.10 x86_64
**Shell:** zsh 5.7.1
**bookwalker-dl version:** 1.3.0

Before using it I made sure to have all the necessary dependencies (bash, cacert, curl and jq) and applied chmod 755 to bw-dl.bash. 

Some [parsing errors](https://i.imgur.com/lFqNxwz.png) occur and in the end [my pages folder is empty](https://i.imgur.com/N081EUH.png), as well as the [metadata.json](https://i.imgur.com/ey5ghxY.png).

[This](https://i.imgur.com/YKSaRjz.png) is what my folder looks like in the end. 

The cid I used is 84893ffb-51c3-44ee-af70-d2d6a9a3df36, which corresponds to [織田信奈の野望　全国版2](https://bookwalker.jp/de84893ffb-51c3-44ee-af70-d2d6a9a3df36/)

**Comment by Atemu** [comment]
That looks like a paid Manga, is it available under the viewer-trial subdomain?

**Comment by jvmunhoz** [comment]
Yes, I just want to download the sample of the light novel. 

The actual link is [https://viewer-trial.bookwalker.jp/03/8/viewer.html?cid=84893ffb-51c3-44ee-af70-d2d6a9a3df36&cty=0](https://viewer-trial.bookwalker.jp/03/8/viewer.html?cid=84893ffb-51c3-44ee-af70-d2d6a9a3df36&cty=0)

**Comment by Atemu** [comment]
That link redirects me to https://viewer-trial.bookwalker.jp/03/8/viewer.html?cty=0 and loads indefinitely, where did you find it? 

It might require a cookie or referrer you get from the page before it.

**Comment by jvmunhoz** [comment]
You can check the sample from pretty much every light novel on BookWalker by pressing on their cover on the store page. This one specifically I accessed through [this page](https://bookwalker.jp/de84893ffb-51c3-44ee-af70-d2d6a9a3df36/). Just click on the cover and you should be redirected to the same page I linked to you above.

**PS:** Try not being logged in to BookWalker, if you are it may attempt to redirect you to the 10m read trial of the whole book instead of just the sample.

**Edit:** The link should be [https://bookwalker.jp/de84893ffb-51c3-44ee-af70-d2d6a9a3df36/?sample=1](https://bookwalker.jp/de84893ffb-51c3-44ee-af70-d2d6a9a3df36/?sample=1). Then it should transfer you to the link I posted on my previous post.

**Comment by Atemu** [comment]
I had a look, apparently they use a different URL structure. Not sure if this was always like this because this tool was made to make a private copy of the Yomureba ~~200~~400 book promotion.

Could you try again with this branch?

https://github.com/Atemu/bookwalker-dl/tree/tameshi

**Comment by jvmunhoz** [comment]
Thanks, now it works perfectly! 

Now just a question, how are the cover and illustrations pages image resolution decided? Are they the actual stored images from Bookwalker?

**Comment by Atemu** [comment]
Yup, all the script really does is parse the metadata to get the locations of the images which the browser viewer would fetch and pass those to `curl` in a fancy loop.

**Comment by jvmunhoz** [comment]
Nice, thank you very much for your help. I'll be closing the issue since the problem has been solved.

**Comment by jvmunhoz** [comment]
So, I was kinda hasty when affirming it worked. Apparently it works ONLY for the cid 84893ffb-51c3-44ee-af70-d2d6a9a3df36. When testing with other cids, the same errors as before happen. 

I tested with 5 other e-books. Take [the next volume of the one it worked](https://bookwalker.jp/deb34e17ec-6ee5-4341-9fb1-fd3472c8d571/) for example. The cid is b34e17ec-6ee5-4341-9fb1-fd3472c8d571.

I guess the baseURL may change depending on the e-book. Could you help with me further testing?
