### ISSUE TITLE
Did I use it in the wrong way or ? Could u write an manual or anything?

### ISSUE THREAD

**Issue by AliceSchuberg** [Atemu/bookwalker-dl#8]
https://imgur.com/CHEbMXo

**Comment by Atemu** [comment]
As it says in the README, you need a certain set of dependencies. That includes `jq` which sh tells you it can't find.  
Speaking of which, you probably need to run the script with `bash` too. I did not make sure this script works with a POSIX shell.

If you use Nix, all you have to do to get an environment with all the dependencies is to run `nix-shell`.  
With other package managers you have to build the environment on your own, probably system-wide. The package names should be very similar to those listed in `shell.nix`'s buildInputs.
