### ISSUE TITLE
How to use this tool on Windows?

### ISSUE THREAD

**Issue by dyxang** [Atemu/bookwalker-dl#9]
There is no tutorial，I can not understand
I used Git Bash and entered Sh bw-dl.sh on the command line. then display: 
`Bash: Line 34: JQ: command not found. `
How to download?
Please tell me how to use it. Thank you.

**Comment by Atemu** [comment]
You need to get the dependencies mentioned in the README in your environment somehow.

Users have been able to get it to work on Windows, see https://www.reddit.com/r/LearnJapanese/comments/fjnlm5/i_made_a_script_that_allows_you_to_download_the/fkorjyn/ but, knowing Windows, you probably need to manually download a binary off a website somewhere and click through 10 submenus to get it in your PATH.  

Windows package management is a PITA which is one of the many reasons I avoid it wherever possible; I can't provide support for it.
